---
- name: Install required software
  package:
    name: unzip
    state: present

- name: Set download directory if install only for the user
  set_fact:
    k3s_runtime_dir: "{{ ansible_user_dir }}/bin"
  when: not k3s_for_all_users | bool

- name: Set download directory for all users to use
  set_fact:
    k3s_runtime_dir: "/usr/local/bin"
  when: k3s_for_all_users | bool

- name: Create bin directory in users home if necessary for local install
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/bin"
    state: directory
    mode: 0755
  when: not k3s_for_all_users | bool

- name: Download file
  get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s"
    dest: "/tmp/k3s"
    mode: 0755

- name: Copy file to runtime directory
  copy:
    src: "/tmp/k3s"
    dest: "{{ k3s_runtime_dir }}"
    mode: 0755
    remote_src: yes
