---
- name: Verify
  hosts: all
  gather_facts: true
  vars:
    k3s_for_all_users: true
    command_shell: bash
  tasks:
    - name: Set download directory if install only for the user
      ansible.builtin.set_fact:
        k3s_runtime_dir: "{{ ansible_user_dir }}/bin"
      when: not k3s_for_all_users | bool

    - name: Set download directory for all users to use
      ansible.builtin.set_fact:
        k3s_runtime_dir: "/usr/local/bin"
      when: k3s_for_all_users | bool

    - name: Find the k3s file
      ansible.builtin.stat:
        path: "{{ k3s_runtime_dir }}/k3s"
      register: k3s_file

    - name: Print stat info
      ansible.builtin.debug:
        msg: "{{ k3s_file.stat }}"

    - name: Assert that k3s exists
      ansible.builtin.assert:
        that: k3s_file.stat.exists

    - name: Assert that k3s is executable
      ansible.builtin.assert:
        that: k3s_file.stat.executable
